services:
  web:
    build:
      context: ./app
    ports:
      - "8501:8501"
    extra_hosts:
      - ${EXTRA_HOST}
    depends_on:
      - api
      
  api:
    build: 
      context: ./api
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REGISTRY_URL
      - IMAGE_NAME
      - AIRFLOW_BUILD_API_URL
    depends_on:
      - registry

  registry:
    image: registry:2
    ports:
      - "5000:5000"
    volumes:
      - registry-data:/var/lib/registry

volumes:
  registry-data: